import { createHash, randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, readdir, rename, rm, stat } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { once } from 'node:events';
import type { Readable } from 'node:stream';
import { finished } from 'node:stream/promises';

export class FileTooLargeError extends Error {
  constructor(readonly limit: number) {
    super(`File exceeds ${limit} bytes`);
  }
}

export interface StoredObject {
  readonly size: number;
  readonly sha256: string;
}

/**
 * Where file bytes live: a directory on the company machine, or an object store in the cloud.
 * Keys are generated by the platform (never user file names). Writes are all-or-nothing.
 */
export interface ObjectStorage {
  /** Streams `source` into `key`, enforcing `maxBytes`, and returns its size and SHA-256. */
  put(key: string, source: Readable, maxBytes: number): Promise<StoredObject>;
  get(key: string): Promise<Readable>;
  stat(key: string): Promise<{ size: number; modifiedAt: Date } | null>;
  /** Copies an object; repeating the same copy is harmless. */
  copy(fromKey: string, toKey: string): Promise<void>;
  /** Removing a missing key is not an error. */
  delete(key: string): Promise<void>;
  list(prefix: string): AsyncIterable<{ key: string; modifiedAt: Date }>;
}

const KEY_PATTERN = /^[a-z0-9][a-z0-9-]*(\/[a-z0-9][a-z0-9-]*)*$/;

export function assertSafeKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.length > 300) throw new Error(`Unsafe storage key: ${key}`);
}

/** Filesystem storage for on-premise installs. Writes go to a temp file, then an atomic rename. */
export class FileSystemStorage implements ObjectStorage {
  constructor(readonly root: string) {}

  private path(key: string): string {
    assertSafeKey(key);
    return join(this.root, 'objects', ...key.split('/'));
  }

  private async tempPath(): Promise<string> {
    const dir = join(this.root, 'tmp');
    await mkdir(dir, { recursive: true });
    return join(dir, randomUUID());
  }

  async put(key: string, source: Readable, maxBytes: number): Promise<StoredObject> {
    const target = this.path(key);
    const temp = await this.tempPath();
    const hash = createHash('sha256');
    const out = createWriteStream(temp, { flags: 'wx' });
    let size = 0;
    let tooLarge = false;
    try {
      for await (const chunk of source) {
        size += (chunk as Buffer).length;
        // Past the limit keep reading (and discarding) so the sender gets a clear answer instead of a
        // dropped connection; nothing more is written to disk.
        if (tooLarge || size > maxBytes) {
          tooLarge = true;
          continue;
        }
        hash.update(chunk as Buffer);
        if (!out.write(chunk)) await once(out, 'drain');
      }
      out.end();
      await finished(out);
      if (tooLarge) throw new FileTooLargeError(maxBytes);
      await mkdir(dirname(target), { recursive: true });
      await rename(temp, target);
    } catch (error) {
      out.destroy();
      await rm(temp, { force: true });
      throw error;
    }
    return { size, sha256: hash.digest('hex') };
  }

  async get(key: string): Promise<Readable> {
    const path = this.path(key);
    await stat(path); // throws ENOENT before a stream is handed out
    return createReadStream(path);
  }

  async stat(key: string): Promise<{ size: number; modifiedAt: Date } | null> {
    try {
      const s = await stat(this.path(key));
      return { size: s.size, modifiedAt: s.mtime };
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  }

  async copy(fromKey: string, toKey: string): Promise<void> {
    const source = await this.get(fromKey);
    await this.put(toKey, source, Number.MAX_SAFE_INTEGER);
  }

  async delete(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }

  async *list(prefix: string): AsyncIterable<{ key: string; modifiedAt: Date }> {
    const base = join(this.root, 'objects');
    const start = join(base, ...prefix.split('/').filter(Boolean));
    const walk = async function* (dir: string): AsyncIterable<{ key: string; modifiedAt: Date }> {
      let entries;
      try {
        entries = await readdir(dir, { withFileTypes: true });
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
        throw error;
      }
      for (const e of entries) {
        const full = join(dir, e.name);
        if (e.isDirectory()) yield* walk(full);
        else yield { key: relative(base, full).split(sep).join('/'), modifiedAt: (await stat(full)).mtime };
      }
    };
    yield* walk(start);
  }
}

/** Hashes an object's current bytes (used to verify before trusting them). */
export async function hashObject(storage: ObjectStorage, key: string): Promise<StoredObject> {
  const hash = createHash('sha256');
  let size = 0;
  for await (const chunk of await storage.get(key)) {
    size += (chunk as Buffer).length;
    hash.update(chunk as Buffer);
  }
  return { size, sha256: hash.digest('hex') };
}
